version: '3.3'
services:    
    api:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: api
        image: appredisapi:latest
        environment:
          ASPNETCORE_ENVIRONMENT: Production
          RedisConnection: 'redis:6379,user=default,password=123456,ssl=False,abortConnect=False'
        ports:
            - 80:80
        networks:
            - appredisapi_network
    redis:
        container_name: redis
        image: redis/redis-stack:latest
        command: redis-server --requirepass ${REDIS_PASSWORD}
        networks:
            - appredisapi_network
            

networks:
    appredisapi_network:
        name: appredisapi_network
        driver: bridge